# $(DEVICE_PATH)/bootimg.mk
LOCAL_PATH := $(call my-dir)

ifneq ($(strip $(TARGET_PREBUILT_DTB)),)
    BOARD_PREBUILT_DTBIMAGE_DIR := $(TARGET_PREBUILT_DTB)
endif

$(INSTALLED_DTBOIMAGE_TARGET):
	@cp $(BOARD_PREBUILT_DTBOIMAGE) $@
